if __name__ == '__main__':
    print("Hello, World!?!")
    print("Hello, World!?!")
    print("hi, git!")
    print("Te pup Miro")
    print("hi, git!")
    print("Hello HElloHello HElloHello HElloHello HElloHello HElloHello HElloHello HEllo")
    print("Opris Claudiu-Daniel -Bunaaaaa")
    print("test Moraru Mihai Andrei")
    print('Buna ziua')